"""rename_mode_to_is_mock

Revision ID: 5a9cdcf4d9c1
Revises: 0002_token_revocation
Create Date: 2026-07-05 19:58:09.311609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9cdcf4d9c1'
down_revision: Union[str, None] = '0002_token_revocation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collector_runs', sa.Column('is_mock', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('collector_runs', 'mode')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.add_column('collector_runs', sa.Column('mode', sa.VARCHAR(length=16), server_default=sa.text("'demo'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('collector_runs', 'is_mock')
    # ### end Alembic commands ###
