"""PDF generation using ReportLab."""
from datetime import date, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _fmt_bytes(n: int | None) -> str:
    if not n:
        return "-"
    units = ["B", "KB", "MB", "GB", "TB"]
    size = float(n)
    for u in units:
        if size < 1024 or u == units[-1]:
            return f"{size:.1f} {u}"
        size /= 1024
    return f"{n}"


def build_report_pdf(
    file_path: str,
    *,
    date_from: date,
    date_to: date,
    nas_filter: str | None,
    logs: list,
    monitoring: list,
    generated_by_name: str,
) -> None:
    """Render the backup report PDF to `file_path`.

    `logs` is a list of BackupLog rows; `monitoring` is a list of latest source
    snapshot dicts (as produced by monitor_service.latest_snapshot).
    """
    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    h2 = styles["Heading2"]
    normal = styles["Normal"]

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        title="Backup Monitoring Report",
    )
    story = []

    # --- Header ---
    story.append(Paragraph("Backup Monitoring Report", title_style))
    story.append(Paragraph("PT Lucky Mom Indonesia", normal))
    story.append(Spacer(1, 6))
    meta = [
        f"<b>Period:</b> {date_from.isoformat()} — {date_to.isoformat()}",
        f"<b>NAS filter:</b> {nas_filter or 'All'}",
        f"<b>Generated by:</b> {generated_by_name}",
        f"<b>Generated at:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ]
    for m in meta:
        story.append(Paragraph(m, normal))
    story.append(Spacer(1, 12))

    # --- Summary ---
    total = len(logs)
    success = sum(1 for l in logs if l.status == "SUCCESS")
    failed = sum(1 for l in logs if l.status == "FAILED")
    unack = sum(1 for l in logs if l.status == "FAILED" and not l.acknowledged)

    story.append(Paragraph("Backup Summary", h2))
    summary_data = [
        ["Total Backups", "Success", "Failed", "Failed (unacknowledged)"],
        [str(total), str(success), str(failed), str(unack)],
    ]
    summary_table = Table(summary_data, colWidths=[42 * mm] * 4)
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 14))

    # --- Backup log list ---
    story.append(Paragraph("Backup Logs", h2))
    if logs:
        rows = [["ID", "NAS", "Job", "Status", "Size", "Started"]]
        for l in logs:
            rows.append(
                [
                    str(l.id),
                    l.nas_id,
                    l.job_name,
                    l.status,
                    _fmt_bytes(l.total_size_bytes),
                    l.started_at.strftime("%Y-%m-%d %H:%M") if l.started_at else "-",
                ]
            )
        t = Table(rows, colWidths=[12 * mm, 30 * mm, 34 * mm, 20 * mm, 24 * mm, 34 * mm])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#374151")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(t)
    else:
        story.append(Paragraph("No backup logs in this period.", normal))
    story.append(Spacer(1, 14))

    # --- Failed logs detail ---
    failed_logs = [l for l in logs if l.status == "FAILED"]
    story.append(Paragraph("Failed Backups", h2))
    if failed_logs:
        rows = [["ID", "NAS", "Job", "Ack", "Message"]]
        for l in failed_logs:
            rows.append(
                [
                    str(l.id),
                    l.nas_id,
                    l.job_name,
                    "Yes" if l.acknowledged else "No",
                    (l.message or "-")[:60],
                ]
            )
        t = Table(rows, colWidths=[12 * mm, 28 * mm, 30 * mm, 14 * mm, 74 * mm])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#7f1d1d")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(t)
    else:
        story.append(Paragraph("No failed backups in this period. ", normal))
    story.append(Spacer(1, 14))

    # --- Monitoring snapshot ---
    story.append(Paragraph("Latest Monitoring Snapshot", h2))
    if monitoring:
        rows = [["Source", "Type", "Status", "Last Collected"]]
        for s in monitoring:
            lc = s.get("last_collected_at")
            rows.append(
                [
                    s.get("display_name", s.get("source_id", "-")),
                    s.get("source_type", "-"),
                    s.get("status", "-"),
                    lc.strftime("%Y-%m-%d %H:%M") if lc else "-",
                ]
            )
        t = Table(rows, colWidths=[46 * mm, 24 * mm, 24 * mm, 40 * mm])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#374151")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(t)
    else:
        story.append(Paragraph("No monitoring data available.", normal))

    doc.build(story)
